### ISSUE TITLE
As a player I want to be able to place my five ships on the battlefield to play the game and have targets to shoot at..

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#1]
Acceptance criteria:
- [x] Upon selecting the field, a ship must be placed there.
- [x] Each player must place all five ships on their own field.
- [x] Boats should not be placed on each other.
- [x] Once the game has commenced, the boats' positions cannot be altered.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#9
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#10
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#11
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#12
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-client#13
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#61
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#62
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#63
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#64
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#65
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#66
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#67
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#68
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#69

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets
