### ISSUE TITLE
As a player I want to know what fields I already shot so that games will not go on infinitely long.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#10]
Acceptance criteria:
- [x] Upon selecting a field, said field should be marked.
- [x] Marked fields should not be able to be shot again.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#42
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#122
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#123
