### ISSUE TITLE
As a player I want to know when I sunk an enemy ship, so that I don’t waste another shot for the already sunken ship.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#11]
Acceptance criteria:
- [x] Upon successful sinking of an enemy ship the ship should appear on the enemy field and the ship should be marked as "sunken".

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#43
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#44
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#126

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets
