### ISSUE TITLE
As a player I want to be able to rotate my ships horizontally or vertically at the start of the game, so that I can make use of the whole field and work out my strategy.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#12]
Acceptance criteria:
- [ ] With inputs in the ship table, the ship's orientation should be changeable.
- [ ] The current orientation of the ship should be visible.
- [ ] The ships cannot be placed diagonally.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#47
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#45
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#46
