### ISSUE TITLE
As a Player I want to be able to hear Sound effects in order to have instant feedback of what is going on during the game.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#13]
Acceptance criteria:
- [ ] The game should play audio in different scenarios of the game.
- [ ] Shooting sound should be played when shooting.
- [ ] Hitting, missing and sinking ships should each give different satisfying audio cues.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#48
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#49
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#50
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-client#51
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#83
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#134
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#135
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#136

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets
