### ISSUE TITLE
As a player I want to create my own lobby to play with friends.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#2]
Acceptance Criteria:
- [x] A player should be able to create a lobby.
- [x] A player should be able to select between joining and hosting a lobby.
- [x] A player should receive a randomly generated pin after creating a lobby.
- [x] A player can join a lobby by entering the pin.
- [x] A player can register.
- [x] A player can login.
Development Task:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#14
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#15
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#16
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#17
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#74
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#75
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#76
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#77
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#78
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#79
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#80
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#85
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#52
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#75
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#74
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#76
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#77
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#167
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#166
