### ISSUE TITLE
As a player I want to know whether I hit something to know where to place my next shot, so that I can sink the hit ship.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#5]
Acceptance criteria:
- [x] After each shot was taken, the player that took a shot should be notified whether they hit or missed the opponent's ships.
- [x] Hit and missed fields should be able to be distinguished from each other.

Development tasks:
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-client#20
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#21
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#22
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#23
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#91

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets
