### ISSUE TITLE
As a player I want to know when I have sunk all the opponent’s ships, so that I know when I won.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#6]
Acceptance criteria:
- [x] Upon destroying all enemy ships, the game should end.
- [x] The Winner should receive a message that they won.
- [x] The Loser should receive a message that they lost.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#24
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#25
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#26
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#95
