### ISSUE TITLE
As a player I want to be able to select between five different sized ships in order to work out my strategy.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#7]
Acceptance criteria:
- [ ] A player should be able to select between the ships.
- [ ] The player can choose between the ships: Carrier 5 squares, Battleship 4 squares, Cruiser 3 squares, Submarine 3 squares, Destroyer 2 squares.
- [ ] The currently selected ship should be highlighted for the player.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#96
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#97
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#98
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#99
- [x] sopra-fs23-group-11/sopra-fs23-group-11-server#100
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#27
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#28
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#29
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#30
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#31
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#32
