### ISSUE TITLE
As a player I don’t want my enemy to see my ships for an exciting battle and to prevent cheating!

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-server#9]
Acceptance criteria:
- [ ] A player is able to see the opponents empty 10 by 10 squared grided field.
- [ ] The enemy’s field should not show the location of the ships.

Development tasks:
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#38
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#39
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#40
- [x] sopra-fs23-group-11/sopra-fs23-group-11-client#41
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#118
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#119
- [ ] sopra-fs23-group-11/sopra-fs23-group-11-server#120

**Comment by Olabi98** [comment]
some tasks were deleted/ replaced by either defining other functionality which satisfy the purpose or doing it using websockets
